// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type InvoiceStatus struct {
	Status string `json:"status"`
}

type Invoices struct {
	ID     int32          `json:"id"`
	UserID sql.NullInt32  `json:"user_id"`
	Status sql.NullString `json:"status"`
	Label  string         `json:"label"`
	Amount int64          `json:"amount"`
}

type Users struct {
	ID        int32  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Balance   int64  `json:"balance"`
}
